// Code generated by llcppg; DO NOT EDIT.

package libcxx

type InitializerList[_Ep any] struct {
	__Begin_ *_Ep
	__Size_  X__1SizeT
}
type InitializerListReference[_Ep any] = *_Ep
type InitializerListConstReference[_Ep any] = *_Ep
type InitializerListSizeType[_Ep any] = X__1SizeT
type InitializerListIterator[_Ep any] = *_Ep
type InitializerListConstIterator[_Ep any] = *_Ep
