// Code generated by llcppg; DO NOT EDIT.

package libcxx

import "github.com/goplus/lib/c"

type X__1FloatRoundStyle c.Int

const (
	__1_roundIndeterminate     X__1FloatRoundStyle = -1
	__1_roundTowardZero        X__1FloatRoundStyle = 0
	__1_roundToNearest         X__1FloatRoundStyle = 1
	__1_roundTowardInfinity    X__1FloatRoundStyle = 2
	__1_roundTowardNegInfinity X__1FloatRoundStyle = 3
)

type X__1FloatDenormStyle c.Int

const (
	__1_denormIndeterminate X__1FloatDenormStyle = -1
	__1_denormAbsent        X__1FloatDenormStyle = 0
	__1_denormPresent       X__1FloatDenormStyle = 1
)
