// Code generated by llcppg; DO NOT EDIT.

package libcxx

import "github.com/goplus/lib/c"

type X__1__Identity struct {
}
type X__1__IdentityIsTransparent = c.Void
type X__1__UnaryFunctionKeepLayoutBase[_Arg any, _Result any] struct {
}
type X__1_PairT struct {
	First  X__1SizeT
	Second X__1SizeT
}
type X__1__BinaryFunctionKeepLayoutBase[_Arg1 any, _Arg2 any, _Result any] struct {
}
