// Code generated by llcppg; DO NOT EDIT.

package std

import "github.com/goplus/lib/c"

type X__1IstreambufIteratorIteratorCategory[_CharT any, _Traits any] = X__1InputIteratorTag
type X__1IstreambufIteratorPointer[_CharT any, _Traits any] = *_CharT
type X__1OstreambufIteratorIteratorCategory[_CharT any, _Traits any] = X__1OutputIteratorTag
type X__1OstreambufIteratorValueType[_CharT any, _Traits any] = c.Void
type X__1OstreambufIteratorDifferenceType[_CharT any, _Traits any] = c.Void
type X__1OstreambufIteratorPointer[_CharT any, _Traits any] = c.Void
type X__1OstreambufIteratorReference[_CharT any, _Traits any] = c.Void
