// Code generated by llcppg; DO NOT EDIT.

package std

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const X_LIBCPP_TYPEINFO_COMPARISON_IMPLEMENTATION = 3

type X__TypeInfoImplementations__StringImplBase struct {
}
type X__TypeInfoImplementations__StringImplBase__TypeNameT = *c.Char
type X__TypeInfoImplementations__UniqueImpl struct {
	X__TypeInfoImplementations__StringImplBase
}
type X__TypeInfoImplementations__NonUniqueImpl struct {
	X__TypeInfoImplementations__StringImplBase
}
type X__TypeInfoImplementations__NonUniqueArmRttiBitImpl struct {
}
type UintptrT = c.UintptrT
type X__TypeInfoImplementations__NonUniqueArmRttiBitImpl__TypeNameT = UintptrT
type X__TypeInfoImplementations__Impl = X__TypeInfoImplementations__NonUniqueArmRttiBitImpl
type TypeInfo struct {
	_xgo_vptr  unsafe.Pointer
	__TypeName X__TypeInfoImplementations__NonUniqueArmRttiBitImpl__TypeNameT
}
type BadCast struct {
	Exception
}
type BadTypeid struct {
	Exception
}

// llgo:type C
type X_vtable_TypeInfo struct {
	XGo_dtor          func(this *TypeInfo)
	XGo_dtor_deleting func(this *TypeInfo)
}

func (p *TypeInfo) XGo_vptr() *X_vtable_TypeInfo {
	return (*X_vtable_TypeInfo)(p._xgo_vptr)
}

// llgo:link (*TypeInfo).XGo_Dtor C._ZNSt9type_infoD1Ev
func (this *TypeInfo) XGo_Dtor() {
}

// llgo:type C
type X_vtable_BadCast struct {
	XGo_dtor          func(this *BadCast)
	XGo_dtor_deleting func(this *BadCast)
	What              func(this *BadCast) *c.Char
}

func (p *BadCast) XGo_vptr() *X_vtable_BadCast {
	return (*X_vtable_BadCast)(*(*unsafe.Pointer)(unsafe.Pointer(p)))
}

// llgo:link (*BadCast).XGo_Ctor__0 C._ZNSt8bad_castC1Ev
func (this *BadCast) XGo_Ctor__0() {
}

// llgo:link (*BadCast).XGo_Dtor C._ZNSt8bad_castD1Ev
func (this *BadCast) XGo_Dtor() {
}

// llgo:link (*BadCast).What C._ZNKSt8bad_cast4whatEv
func (this *BadCast) What() *c.Char {
	return nil
}

// llgo:type C
type X_vtable_BadTypeid struct {
	XGo_dtor          func(this *BadTypeid)
	XGo_dtor_deleting func(this *BadTypeid)
	What              func(this *BadTypeid) *c.Char
}

func (p *BadTypeid) XGo_vptr() *X_vtable_BadTypeid {
	return (*X_vtable_BadTypeid)(*(*unsafe.Pointer)(unsafe.Pointer(p)))
}

// llgo:link (*BadTypeid).XGo_Ctor__0 C._ZNSt10bad_typeidC1Ev
func (this *BadTypeid) XGo_Ctor__0() {
}

// llgo:link (*BadTypeid).XGo_Dtor C._ZNSt10bad_typeidD1Ev
func (this *BadTypeid) XGo_Dtor() {
}

// llgo:link (*BadTypeid).What C._ZNKSt10bad_typeid4whatEv
func (this *BadTypeid) What() *c.Char {
	return nil
}
