// Code generated by llcppg; DO NOT EDIT.

package std

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

type X__1__VariantDetail_Trait c.Int

const (
	X__1__VariantDetail_Trait__TriviallyAvailable X__1__VariantDetail_Trait = 0
	X__1__VariantDetail_Trait__Available          X__1__VariantDetail_Trait = 1
	X__1__VariantDetail_Trait__Unavailable        X__1__VariantDetail_Trait = 2
)

type BadVariantAccess struct {
	Exception
}
type X__1__VariantDetail__ValuelessT struct {
}
type X__1__VariantDetail__Access__Union struct {
}
type X__1__VariantDetail__Access__Base struct {
}
type X__1__VariantDetail__Access__Variant struct {
}
type X__1__VariantDetail__Visitation__Base struct {
}
type X__1__VariantDetail__Visitation__Variant struct {
}
type X__1__VariantDetail__Visitation__Variant__ValueVisitor[_Visitor any] struct {
	X__Visitor *_Visitor
}
type X__1__VariantDetail__NoNarrowingCheck struct {
}
type X__1__VariantDetail__NarrowingCheck struct {
}
type X__1__ConvertToBool[_Operator any] struct {
}

// llgo:type C
type X_vtable_BadVariantAccess struct {
	XGo_dtor          func(this *BadVariantAccess)
	XGo_dtor_deleting func(this *BadVariantAccess)
	What              func(this *BadVariantAccess) *c.Char
}

func (p *BadVariantAccess) XGo_vptr() *X_vtable_BadVariantAccess {
	return (*X_vtable_BadVariantAccess)(*(*unsafe.Pointer)(unsafe.Pointer(p)))
}

// llgo:link (*BadVariantAccess).What C._ZNKSt18bad_variant_access4whatEv
func (this *BadVariantAccess) What() *c.Char {
	return nil
}
