// Code generated by llcppg; DO NOT EDIT.

package std

const X_LIBCPP_HAS_ALGORITHM_VECTOR_UTILS = 1
const X_LIBCPP_VECTORIZE_ALGORITHMS = 1

type X__1_Algorithm__Copy struct {
}
type X__1_Algorithm__FillN struct {
}
type X__1_Algorithm__ForEach struct {
}
type X__1__EqualTo struct {
}
type X__1__DebugLess[_Compare any] struct {
	X__Comp_ *_Compare
}
type X__1_ClassicAlgPolicy struct {
}
