// Code generated by llcppg; DO NOT EDIT.

package std

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

type Exception struct {
	_xgo_vptr unsafe.Pointer
}
type BadException struct {
	Exception
}

// llgo:type C
type _xgo_vtable_Exception struct {
	XGo_dtor          func(this *Exception)
	XGo_dtor_deleting func(this *Exception)
	What              func(this *Exception) *c.Char
}

func (p *Exception) XGo_vptr() *_xgo_vtable_Exception {
	return (*_xgo_vtable_Exception)(p._xgo_vptr)
}

// llgo:link (*Exception).XGo_Dtor C._ZNSt9exceptionD1Ev
func (this *Exception) XGo_Dtor() {
}

// llgo:link (*Exception).What C._ZNKSt9exception4whatEv
func (this *Exception) What() *c.Char {
	return nil
}

// llgo:type C
type _xgo_vtable_BadException struct {
	XGo_dtor          func(this *BadException)
	XGo_dtor_deleting func(this *BadException)
	What              func(this *BadException) *c.Char
}

func (p *BadException) XGo_vptr() *_xgo_vtable_BadException {
	return (*_xgo_vtable_BadException)(*(*unsafe.Pointer)(unsafe.Pointer(p)))
}

// llgo:link (*BadException).XGo_Dtor C._ZNSt13bad_exceptionD1Ev
func (this *BadException) XGo_Dtor() {
}

// llgo:link (*BadException).What C._ZNKSt13bad_exception4whatEv
func (this *BadException) What() *c.Char {
	return nil
}
