// Code generated by llcppg; DO NOT EDIT.

package std

import "github.com/goplus/lib/c"

type X__1InputIteratorTag struct {
}
type X__1OutputIteratorTag struct {
}
type X__1ForwardIteratorTag struct {
	X__1InputIteratorTag
}
type X__1BidirectionalIteratorTag struct {
	X__1ForwardIteratorTag
}
type X__1RandomAccessIteratorTag struct {
	X__1BidirectionalIteratorTag
}
type X__1__HasIteratorTypedefs[_Tp any] struct {
}
type X__1Iterator[_Category any, _Tp any, _Distance any, _Pointer any, _Reference any] struct {
}
type X__1__IteratorBase[_Derived any, _Category any, _Tp any, _Distance any, _Pointer any, _Reference any] = X__1Iterator[_Category, _Tp, _Distance, _Pointer, _Reference]
type X__1BackInsertIterator[_Container any] struct {
	X__1__IteratorBase[X__1BackInsertIterator[_Container], X__1OutputIteratorTag, c.Void, c.Void, c.Void, c.Void]
	container *_Container
}
type X__1BackInsertIteratorIteratorCategory[_Container any] = X__1OutputIteratorTag
type X__1BackInsertIteratorValueType[_Container any] = c.Void
type X__1BackInsertIteratorDifferenceType[_Container any] = c.Void
type X__1BackInsertIteratorPointer[_Container any] = c.Void
type X__1BackInsertIteratorReference[_Container any] = c.Void
type X__1FrontInsertIterator[_Container any] struct {
	X__1__IteratorBase[X__1FrontInsertIterator[_Container], X__1OutputIteratorTag, c.Void, c.Void, c.Void, c.Void]
	container *_Container
}
type X__1FrontInsertIteratorIteratorCategory[_Container any] = X__1OutputIteratorTag
type X__1FrontInsertIteratorValueType[_Container any] = c.Void
type X__1FrontInsertIteratorDifferenceType[_Container any] = c.Void
type X__1FrontInsertIteratorPointer[_Container any] = c.Void
type X__1FrontInsertIteratorReference[_Container any] = c.Void
type X__1InsertIteratorIteratorCategory[_Container any] = X__1OutputIteratorTag
type X__1InsertIteratorValueType[_Container any] = c.Void
type X__1InsertIteratorDifferenceType[_Container any] = c.Void
type X__1InsertIteratorPointer[_Container any] = c.Void
type X__1InsertIteratorReference[_Container any] = c.Void
type X__1IstreamIteratorIteratorCategory[_Tp any, _CharT any, _Traits any, _Distance any] = X__1InputIteratorTag
type X__1IstreamIteratorPointer[_Tp any, _CharT any, _Traits any, _Distance any] = *_Tp
type X__1IstreamIteratorReference[_Tp any, _CharT any, _Traits any, _Distance any] = *_Tp
type X__1MoveIterator[_Iter any] struct {
	__Current_ _Iter
}
type X__1OstreamIteratorIteratorCategory[_Tp any, _CharT any, _Traits any] = X__1OutputIteratorTag
type X__1OstreamIteratorValueType[_Tp any, _CharT any, _Traits any] = c.Void
type X__1OstreamIteratorDifferenceType[_Tp any, _CharT any, _Traits any] = c.Void
type X__1OstreamIteratorPointer[_Tp any, _CharT any, _Traits any] = c.Void
type X__1OstreamIteratorReference[_Tp any, _CharT any, _Traits any] = c.Void
type X__1ReverseIterator[_Iter any] struct {
	X__1__IteratorBase
	__T_    _Iter
	current _Iter
}
