// Code generated by llcppg; DO NOT EDIT.

package std

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

type AlignValT X__1SizeT
type BadAlloc struct {
	Exception
}
type BadArrayNewLength struct {
	BadAlloc
}
type NothrowT struct {
}

// llgo:type C
type NewHandler = func()

// llgo:type C
type X_vtable_BadAlloc struct {
	XGo_dtor          func(this *BadAlloc)
	XGo_dtor_deleting func(this *BadAlloc)
	What              func(this *BadAlloc) *c.Char
}

func (p *BadAlloc) XGo_vptr() *X_vtable_BadAlloc {
	return (*X_vtable_BadAlloc)(*(*unsafe.Pointer)(unsafe.Pointer(p)))
}

// llgo:link (*BadAlloc).XGo_Ctor__0 C._ZNSt9bad_allocC1Ev
func (this *BadAlloc) XGo_Ctor__0() {
}

// llgo:link (*BadAlloc).XGo_Dtor C._ZNSt9bad_allocD1Ev
func (this *BadAlloc) XGo_Dtor() {
}

// llgo:link (*BadAlloc).What C._ZNKSt9bad_alloc4whatEv
func (this *BadAlloc) What() *c.Char {
	return nil
}

// llgo:type C
type X_vtable_BadArrayNewLength struct {
	XGo_dtor          func(this *BadArrayNewLength)
	XGo_dtor_deleting func(this *BadArrayNewLength)
	What              func(this *BadArrayNewLength) *c.Char
}

func (p *BadArrayNewLength) XGo_vptr() *X_vtable_BadArrayNewLength {
	return (*X_vtable_BadArrayNewLength)(*(*unsafe.Pointer)(unsafe.Pointer(p)))
}

// llgo:link (*BadArrayNewLength).XGo_Ctor__0 C._ZNSt20bad_array_new_lengthC1Ev
func (this *BadArrayNewLength) XGo_Ctor__0() {
}

// llgo:link (*BadArrayNewLength).XGo_Dtor C._ZNSt20bad_array_new_lengthD1Ev
func (this *BadArrayNewLength) XGo_Dtor() {
}

// llgo:link (*BadArrayNewLength).What C._ZNKSt20bad_array_new_length4whatEv
func (this *BadArrayNewLength) What() *c.Char {
	return nil
}

//go:linkname X__ThrowBadAlloc C._ZSt17__throw_bad_allocv
func X__ThrowBadAlloc()

//go:linkname Nothrow C._ZSt7nothrow
var Nothrow NothrowT

//go:linkname New__0 C._Znwm
func New__0(__sz X__1SizeT) unsafe.Pointer

//go:linkname New__2 C._ZnwmRKSt9nothrow_t
func New__2(__sz X__1SizeT, _llcppg_param2 *NothrowT) unsafe.Pointer

//go:linkname Delete__0 C._ZdlPv
func Delete__0(__p unsafe.Pointer)

//go:linkname Delete__2 C._ZdlPvRKSt9nothrow_t
func Delete__2(__p unsafe.Pointer, _llcppg_param2 *NothrowT)

//go:linkname Delete__3 C._ZdlPvm
func Delete__3(__p unsafe.Pointer, __sz X__1SizeT)

//go:linkname New[]__0 C._Znam
func New[]__0(__sz X__1SizeT) unsafe.Pointer

//go:linkname New[]__2 C._ZnamRKSt9nothrow_t
func New[]__2(__sz X__1SizeT, _llcppg_param2 *NothrowT) unsafe.Pointer

//go:linkname Delete[]__0 C._ZdaPv
func Delete[]__0(__p unsafe.Pointer)

//go:linkname Delete[]__2 C._ZdaPvRKSt9nothrow_t
func Delete[]__2(__p unsafe.Pointer, _llcppg_param2 *NothrowT)

//go:linkname Delete[]__3 C._ZdaPvm
func Delete[]__3(__p unsafe.Pointer, __sz X__1SizeT)

//go:linkname New__3 C._ZnwmSt11align_val_t
func New__3(__sz X__1SizeT, _llcppg_param2 AlignValT) unsafe.Pointer

//go:linkname New__4 C._ZnwmSt11align_val_tRKSt9nothrow_t
func New__4(__sz X__1SizeT, _llcppg_param2 AlignValT, _llcppg_param3 *NothrowT) unsafe.Pointer

//go:linkname Delete__4 C._ZdlPvSt11align_val_t
func Delete__4(__p unsafe.Pointer, _llcppg_param2 AlignValT)

//go:linkname Delete__5 C._ZdlPvSt11align_val_tRKSt9nothrow_t
func Delete__5(__p unsafe.Pointer, _llcppg_param2 AlignValT, _llcppg_param3 *NothrowT)

//go:linkname Delete__6 C._ZdlPvmSt11align_val_t
func Delete__6(__p unsafe.Pointer, __sz X__1SizeT, _llcppg_param3 AlignValT)

//go:linkname New[]__3 C._ZnamSt11align_val_t
func New[]__3(__sz X__1SizeT, _llcppg_param2 AlignValT) unsafe.Pointer

//go:linkname New[]__4 C._ZnamSt11align_val_tRKSt9nothrow_t
func New[]__4(__sz X__1SizeT, _llcppg_param2 AlignValT, _llcppg_param3 *NothrowT) unsafe.Pointer

//go:linkname Delete[]__4 C._ZdaPvSt11align_val_t
func Delete[]__4(__p unsafe.Pointer, _llcppg_param2 AlignValT)

//go:linkname Delete[]__5 C._ZdaPvSt11align_val_tRKSt9nothrow_t
func Delete[]__5(__p unsafe.Pointer, _llcppg_param2 AlignValT, _llcppg_param3 *NothrowT)

//go:linkname Delete[]__6 C._ZdaPvmSt11align_val_t
func Delete[]__6(__p unsafe.Pointer, __sz X__1SizeT, _llcppg_param3 AlignValT)

//go:linkname SetNewHandler C._ZSt15set_new_handlerPFvvE
func SetNewHandler(_llcppg_param1 NewHandler) NewHandler

//go:linkname GetNewHandler C._ZSt15get_new_handlerv
func GetNewHandler() NewHandler
