// Code generated by llcppg; DO NOT EDIT.

package std

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

type AlignValT X__1SizeT
type BadAlloc struct {
	Exception
}
type BadArrayNewLength struct {
	BadAlloc
}
type NothrowT struct {
}

// llgo:type C
type NewHandler = func()

// llgo:type C
type X_vtable_BadAlloc struct {
	XGo_dtor          func(this *BadAlloc)
	XGo_dtor_deleting func(this *BadAlloc)
	What              func(this *BadAlloc) *c.Char
}

func (p *BadAlloc) XGo_vptr() *X_vtable_BadAlloc {
	return (*X_vtable_BadAlloc)(*(*unsafe.Pointer)(unsafe.Pointer(p)))
}

// llgo:link (*BadAlloc).XGo_Ctor__0 C._ZNSt9bad_allocC1Ev
func (this *BadAlloc) XGo_Ctor__0() {
}

// llgo:link (*BadAlloc).XGo_Dtor C._ZNSt9bad_allocD1Ev
func (this *BadAlloc) XGo_Dtor() {
}

// llgo:link (*BadAlloc).What C._ZNKSt9bad_alloc4whatEv
func (this *BadAlloc) What() *c.Char {
	return nil
}

// llgo:type C
type X_vtable_BadArrayNewLength struct {
	XGo_dtor          func(this *BadArrayNewLength)
	XGo_dtor_deleting func(this *BadArrayNewLength)
	What              func(this *BadArrayNewLength) *c.Char
}

func (p *BadArrayNewLength) XGo_vptr() *X_vtable_BadArrayNewLength {
	return (*X_vtable_BadArrayNewLength)(*(*unsafe.Pointer)(unsafe.Pointer(p)))
}

// llgo:link (*BadArrayNewLength).XGo_Ctor__0 C._ZNSt20bad_array_new_lengthC1Ev
func (this *BadArrayNewLength) XGo_Ctor__0() {
}

// llgo:link (*BadArrayNewLength).XGo_Dtor C._ZNSt20bad_array_new_lengthD1Ev
func (this *BadArrayNewLength) XGo_Dtor() {
}

// llgo:link (*BadArrayNewLength).What C._ZNKSt20bad_array_new_length4whatEv
func (this *BadArrayNewLength) What() *c.Char {
	return nil
}

//go:linkname X__ThrowBadAlloc C._ZSt17__throw_bad_allocv
func X__ThrowBadAlloc()

//go:linkname Nothrow C._ZSt7nothrow
var Nothrow NothrowT

//go:linkname SetNewHandler C._ZSt15set_new_handlerPFvvE
func SetNewHandler(_llcppg_param1 NewHandler) NewHandler

//go:linkname GetNewHandler C._ZSt15get_new_handlerv
func GetNewHandler() NewHandler
