// Code generated by llcppg; DO NOT EDIT.

package std

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type X_1_StructDouble struct {
	X_Lx c.LongDouble
}
type X_1_StructDouble4 struct {
	X_Lx [4]c.Double
}
type X_1_Nat struct {
}
type X_1IntegralConstant struct {
}
type X_1RemoveCv struct {
}
type X_1AddConst struct {
}
type X_1AddCv struct {
}
type X_1AddVolatile struct {
}
type X_1RemoveReference struct {
}
type X_1AddPointer struct {
}
type X_1AddLvalueReference struct {
}
type X_1AddRvalueReference struct {
}
type X__1_AlignedAsT[_Tp any] struct {
}

//go:linkname X_1_AlignedStorageMaxAlign C._ZNSt3__127__aligned_storage_max_alignE
var X_1_AlignedStorageMaxAlign c.SizeT

type X_1AlignedStorage struct {
}
type X_1AlignedStorageType struct {
}
type X_1AlignedUnion struct {
}
type X__1Decay struct {
}
type X_1_TypeIdentity[_Tp any] struct {
}
type X_1RemoveAllExtents struct {
}
type X_1_TypeList[_Types any] struct {
}
type X_1MakeSigned struct {
}
type X_1MakeUnsigned struct {
}
type X_1RemoveConst struct {
}
type X_1RemoveX__1Extent struct {
}
type X_1RemovePointer struct {
}
type X_1RemoveVolatile struct {
}

//go:linkname X1AlignedUnionAlignmentValue C._ZNSt3__113aligned_union15alignment_valueE
var X1AlignedUnionAlignmentValue c.SizeT

//go:linkname X1AlignedUnion_Len C._ZNSt3__113aligned_union5__lenE
var X1AlignedUnion_Len c.SizeT
