// Code generated by llcppg; DO NOT EDIT.

package std

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type X_1RemoveCv[_Tp any] struct {
}
type X_1AddConst[_Tp any] struct {
}
type X_1AddCv[_Tp any] struct {
}
type X_1AddVolatile[_Tp any] struct {
}
type X_1RemoveReference[_Tp any] struct {
}
type X_1AddPointer[_Tp any] struct {
}
type X_1AddLvalueReference[_Tp any] struct {
}
type X_1AddRvalueReference[_Tp any] struct {
}
type X_1_AlignedAsT[_Tp any] struct {
}
type X_1__StructDouble struct {
	X_Lx c.LongDouble
}
type X_1__StructDouble4 struct {
	X_Lx [4]c.Double
}
type X_1Decay[_Tp any] struct {
}
type X_1__TypeIdentity[_Tp any] struct {
}
type X_1RemoveAllExtents[_Tp any] struct {
}
type X_1MakeSigned[_Tp any] struct {
}
type X_1MakeUnsigned[_Tp any] struct {
}
type X_1RemoveConst[_Tp any] struct {
}
type X_1RemoveExtent[_Tp any] struct {
}
type X_1RemovePointer[_Tp any] struct {
}
type X_1RemoveVolatile[_Tp any] struct {
}
type X_1__Nat struct {
}

//go:linkname X_1__AlignedStorageMaxAlign C._ZNSt3__127__aligned_storage_max_alignE
var X_1__AlignedStorageMaxAlign X_1SizeT
