// Code generated by llcppg; DO NOT EDIT.

package std

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

//go:linkname X__1__LibcppVerboseAbort C._ZNSt3__122__libcpp_verbose_abortEPKcz
func X__1__LibcppVerboseAbort(__format *c.Char, __llgo_va_list ...any)
